# Generated by Django 2.0.6 on 2018-06-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0003_auto_20180618_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='invite_reson',
            new_name='invite_reason',
        ),
    ]
