# Generated by Django 2.0.6 on 2018-06-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0005_facebookuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(to='manytomany.InstagramUser')),
            ],
        ),
    ]
